### ISSUE TITLE
very simple static routing for "/" doesn't seam to work

### ISSUE THREAD

**Issue by chmike** [gowww/router#3]
The following code doesn't return some files in my ./www directory.
My ./www directory contains two files ./www/index.html and ./www/css/main.css. Note that the css file is in a subdirectory named css. 

When performing a get on http://localhost:8080 I get back the index.html file, but the css file is not returned. 

Here is the code:

``` Go
func main() {
	rt := router.New()
	rt.Get("/", http.FileServer(http.Dir("www")))
	http.ListenAndServe(":8080", rt)
}
```

When using the default server mux, I have no problem. I get the css file and the style is right.

``` Go
func main() {
	http.Handle("/", http.FileServer(http.Dir("www")))
	http.ListenAndServe(":8080", nil)
}
```

**Comment by chmike** [comment]
If I change my code to use your example, and set the path to the css file to /static/css/main.css, then the css is returned. I don't understand why my code above doesn't return the css file. It should work as with the default mux. Although I understand that it doesn't make much sense to do this when there are multiple routes with dynamic content.

``` Go
rt.Get("/static/", http.StripPrefix("/static/", http.FileServer(http.Dir("www"))))
```

**Comment by xthezealot** [comment]
It simply doesn't work because the root path (`/`) doesn't behave like a wildcard. I made it not to.
Otherwise, as with the standard Go mux, we should also put the "404 not found" handler inside `/`'s handler and it would be ugly.

So, no other request path than `/` matches `/`.
The content of `index.html` is only returned because `http.FileServer` implicitly looks for a file named `index.html` when the request path ends with `/`.

---

If you want to serve a file on the root path, the best solution is to make it explicit and have the assets in a subdirectory:

```Go
// New project structure:
//	./www/index.html
//	./www/static/css/main.css

// Serve "/" with the content of index.html.
rt.Get("/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	http.ServeFile(w, r, "www/index.html")
}))

// Serve "/static/css/main.css" and all other assets.
rt.Get("/static/", http.StripPrefix("/static/", http.FileServer(http.Dir("www/static"))))
```

---

Now, if you really don't like the `/static/` prefix, you can still keep your actual project structure and replace the `rt.NotFoundHandler`:

```Go
rt.NotFoundHandler = http.FileServer(http.Dir("www"))
```

Or, more "complicated", put the router inside a middleware: a main handler that starts to call `http.FileServer` and catches the response. If the file server tries to send a 404 error response, null it and give the request to the router.
If I remember well, that's what the [Sinatra](https://github.com/sinatra/sinatra) framework (in Ruby) does.

That said, is it worth to loose performance only to avoid an URL prefix for assets/static files? 

---

N.B. : Even with the standard Go mux, it's a bad idea to use `http.FileServer` on `/` as you'll loose control over "404 not found" errors.

N.B. 2: To reassure you, I can tell you that almost all routers and frameworks in all languages require the static files to have their own path prefix.

**Comment by chmike** [comment]
Thank you. I thought so too. I just met this problem with a trivial and unrealistic example servers. static is fine and the actual defacto convention. Your example in the readme is how to do it.

A short line explaining that in the Readme or doc would help understand the particular behavior of /. and the possible resulting "surprise". I didn't see it. Did I miss it ?

Another small detail regarding the README documentation is that I couldn't find how the path search is ordered. It is said in the beginning that it's smart but I didn't find a more explicit description. Did I miss it too ?  

You may close the Issue if you want.

**Comment by xthezealot** [comment]
OK, I will clarify that the root path is not a wildcard.

> [...] how the path search is ordered.

That's an implementation detail.
I don't think it's interesting to have that in READMEs.

> It is said in the beginning that it's smart [...]

The *Smart prioritized routes* feature only means that we can use static, named and wildcard routes on the same level, without conflict (cf. the *No surprise* sections).


Thank you!
